import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Inter as FontSans } from "next/font/google";
import { Providers } from "@/components/providers/providers";
import { ThemeToggle } from "@/components/theme-toggle";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen min-w-screen bg-background font-sans antialiased flex justify-center",
          fontSans.variable
        )}
      >
        <Providers>
          <div className="w-screen flex flex-col max-w-[1400px] items-center">
            <nav className="w-full flex items-center justify-end py-3">
              <ThemeToggle />
            </nav>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
